INSERT INTO Genre(name)
VALUES
('AOR'),
('Acid House'),
('Acid Jazz'),
('Acid Pop'),
('Acid Rock'),
('Acoustic Rock'),
('Adult Contemporary'),
('Afrofunk'),
('Alternative Country'),
('Alternative Dance'),
('Alternative Hip Hop'),
('Alternative Metal'),
('Alternative Pop'),
('Alternative Rock'),
('Ambient'),
('Anarcho-Punk'),
('Arena Rock'),
('Art Pop'),
('Art Punk'),
('Art Rock'),
('Aussie Rock'),
('Avant-Funk'),
('Avant-Garde'),
('Avant-Garde Jazz'),
('Avant-Garde Metal'),
('Avant-Garde Punk'),
('Avant-Pop'),
('Balkan'),
('Ballad'),
('Baroque Pop'),
('Baroque Rock'),
('Beach Rock'),
('Beat'),
('Bedroom Pop'),
('Big Band'),
('Big Beat'),
('Biker Metal'),
('Black Metal'),
('Blackened Crust'),
('Blackened Death Metal'),
('Blue-Eyed Soul'),
('Blues'),
('Blues Rock'),
('Boogie Rock'),
('Boogie-Woogie'),
('Breakbeat Hardcore'),
('Britpop'),
('Brutal Death Metal'),
('Bubblegum'),
('Bubblegum Pop'),
('Cabaret'),
('Celtic Punk'),
('Chamber Pop'),
('Chicago Blues'),
('Chicano Rock'),
('Children''s Song'),
('Christian Hardcore'),
('Christian Metal'),
('Christian Rock'),
('Christmas Music'),
('Chúntaro'),
('Classical'),
('College Rock'),
('Comedy Rock'),
('Conscious Hip Hop'),
('Contemporary Classical Music'),
('Country'),
('Country Blues'),
('Country Folk'),
('Country Pop'),
('Country Rock'),
('Cowpunk'),
('Crossover Thrash'),
('Crust Punk'),
('Cumbia'),
('Cumbia Sinfónica'),
('Dance'),
('Dance Pop'),
('Dance Punk'),
('Dance Rock'),
('Dark Ambient'),
('Dark Wave'),
('Death Metal'),
('Death Rock'),
('Deathcore'),
('Desert Rock'),
('Digital Hardcore'),
('Disco'),
('Disco Rock'),
('Doo-Wop'),
('Doom Metal'),
('Dream Pop'),
('Drone'),
('Drum and Bass'),
('Dub'),
('Dubstep'),
('Dungeon Synth'),
('EDM'),
('East Rock Hip Hop'),
('Easy Listening'),
('Easycore'),
('Electric Blues'),
('Electro House'),
('Electro-Industrial'),
('Electroclash'),
('Electronic'),
('Electronic Rock'),
('Electronicore'),
('Electropop'),
('Electropunk'),
('Emo'),
('Epic Doom Metal'),
('Europop'),
('Experimental Dub'),
('Experimental Metal'),
('Experimental Pop'),
('Experimental Rock'),
('Extreme Metal'),
('Film Score'),
('Folk'),
('Folk Metal'),
('Folk Pop'),
('Folk Punk'),
('Folk Rock'),
('Folktronica'),
('Freak Folk'),
('Freakbeat'),
('Free Improvisation'),
('Free Jazz'),
('Funk'),
('Funk Metal'),
('Funk Rock'),
('Funky House'),
('Fusion'),
('Future Funk'),
('Gangsta Rap'),
('Garage Pop'),
('Garage Punk'),
('Garage Rock'),
('Garage Rock Revival'),
('Geek Punk'),
('Geek Rock'),
('Glam Metal'),
('Glam Punk'),
('Glam Rock'),
('Gospel'),
('Gothabilly'),
('Gothic Metal'),
('Gothic Rock'),
('Grebo'),
('Grindcore'),
('Groove Metal'),
('Grunge'),
('Gypsy Punk'),
('Hard Rock'),
('Hardcore Hip Hop'),
('Hardcore Punk'),
('Hardcore Techno'),
('Heavy Metal'),
('Hip Hop'),
('Horror Punk'),
('Hot Rod Rock'),
('House'),
('Hyperpop'),
('Indie'),
('Indie Electronic'),
('Indie Pop'),
('Indie Rock'),
('Indietronica'),
('Industrial'),
('Industrial Dance'),
('Industrial Metal'),
('Industrial Rock'),
('Instrumental'),
('Instrumental Rock'),
('Irish Folk'),
('Jam Band'),
('Jangle'),
('Jangle Pop'),
('Jazz'),
('Jazz Funk'),
('Jazz Fusion'),
('Jazz Rap'),
('Jazz Rock'),
('Jump Blues'),
('Krautrock'),
('Kwaito'),
('Lo-Fi'),
('Lounge'),
('Lounge Pop'),
('Madchester'),
('Math Rock'),
('Medieval'),
('Melodic Black Metal'),
('Melodic Death Metal'),
('Melodic Hardcore'),
('Metal'),
('Metalcore'),
('Minimalist'),
('Mod Pop'),
('Music Hall'),
('Musical Theatre'),
('Musique Concréte'),
('NWOBHM'),
('Neo-Classic'),
('Neo-Folk'),
('Neo-Medieval Music'),
('Neo-Psychedelia'),
('Neo-Rockabilly'),
('Neo-Soul'),
('Neoclassical Metal'),
('New Age'),
('New Jack Swing'),
('New Rave'),
('New Romantic'),
('New Wave'),
('No Wave'),
('Noise Pop'),
('Noise Rock'),
('Nu Disco'),
('Nu Gaze'),
('Nu Metal'),
('Occult Rock'),
('Oi!'),
('Operatic Pop'),
('Orchestral'),
('Orchestral Pop'),
('Orchestral Rock'),
('Poetry'),
('Pop'),
('Pop Metal'),
('Pop Punk'),
('Pop Rap'),
('Pop Rock'),
('Post-Britpop'),
('Post-Disco'),
('Post-Grunge'),
('Post-Hardcore'),
('Post-Metal'),
('Post-Prog'),
('Post-Psychedelia'),
('Post-Punk'),
('Post-Punk Revival'),
('Post-Rock'),
('Power Metal'),
('Power Pop'),
('Progressive Black Metal'),
('Progressive Folk'),
('Progressive Metal'),
('Progressive Pop'),
('Progressive Rock'),
('Progressive Soul'),
('Proto-Metal'),
('Proto-Prog'),
('Proto-Punk'),
('Psychedelia'),
('Psychedelic Folk'),
('Psychedelic Funk'),
('Psychedelic Pop'),
('Psychedelic Rock'),
('Psychedelic Soul'),
('Psychobilly'),
('Pub Rock'),
('Punk Blues'),
('Punk Jazz'),
('Punk Metal'),
('Punk Rap'),
('Punk Rock'),
('Raga Rock'),
('Raggamuffin'),
('Rap Metal'),
('Rap Rock'),
('Rapcore'),
('Rave'),
('Reggae'),
('Reggae Fusion'),
('Reggae Rock'),
('Reggaeton'),
('Rhythm and Blues'),
('Rock'),
('Rock Opera'),
('Rock and Roll'),
('Rock en Español'),
('Rockabilly'),
('Rocksteady'),
('Roots Reggae'),
('Roots Rock'),
('Sad Pop'),
('Samba Reggae'),
('Schlager'),
('Sci-Fi'),
('Shock Rock'),
('Shoegazing'),
('Show Tune'),
('Ska'),
('Ska Punk'),
('Skate Punk'),
('Slowcore'),
('Sludge Metal'),
('Soft Rock'),
('Sophisti-Pop'),
('Soul'),
('Soul Jazz'),
('Sound Collage'),
('Southern Gothic'),
('Southern Rock'),
('Space Music'),
('Space Pop'),
('Space Rock'),
('Speed Metal'),
('Spoken Word'),
('Stoner Rock'),
('Street Punk'),
('Sunshine Pop'),
('Surf'),
('Surf Punk'),
('Surf Rock'),
('Swamp Rock'),
('Swing'),
('Symphonic Black Metal'),
('Symphonic Metal'),
('Symphonic Pop'),
('Symphonic Power Metal'),
('Symphonic Rock'),
('Synth-Pop'),
('Synth-Rock'),
('Technical Death Metal'),
('Technical Thrash Metal'),
('Techno'),
('Teen Pop'),
('Tex-Mex'),
('Texas Blues'),
('Thrash Metal'),
('Traditional Pop'),
('Trance'),
('Trip Hop'),
('Twee Pop'),
('Underground Hip Hop'),
('Urban'),
('Urban Rock'),
('Vaporwave'),
('Viking Metal'),
('World'),
('Worldbeat'),
('Yacht Rock'),
